apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: run-oc-cronjob
spec:
    schedule: "*/1 * * * *" # run every five minutes
    jobTemplate:
      spec:
        template:
          spec:
            serviceAccountName: cronjob-sa # use the service account
            containers:
            - name: run-oc
              image: quay.io/openshift/origin-cli # use the image from the repositor
              env:
              - name: OC_COMMANDS_FILE # specify the environment variable for the file name
                value: /home/student/cronjob_Healthcheck/hcvol/oc-commands.txt
              volumeMounts:
              - name: hcvol # mount the host folder as a volume
                mountPath: /home/student/cronjob_Healthcheck/hcvol/
            volumes:
            - name: hcvol
              hostPath:
                path: /home/student/cronjob_Healthcheck/hcvol # specify the path of the host folder
                type: DirectoryOrCreate # create if not exists
            restartPolicy: OnFailure
